### ISSUE TITLE
Expose X509.Certificate.compare

### ISSUE THREAD

**Issue by cfcs** [mirleft/ocaml-x509#116]
It would be pretty useful to have this, both to enable use in maps/sets, but also to be able to determine equality.

My use case is serializing a state to a file and performing sanity checking of this.

What I currently do is re-encoding both certificates to DER and comparing the result of that, but I guess that's a bit inefficient, and it's a bit silly to have to extend the `X509.Certificate` module everywhere I need to do this.

**Comment by hannesm** [comment]
hmm, but in certificate.ml there is no definition of `compare`. I'm wondering whether the use-case of storing certificates in maps/sets is common, and we should provide a `compare`?

**Comment by cfcs** [comment]
Reconsidering this, I think you're right that most uses in `Map` or `Set` is likely going to be using a custom `compare` to be useful. Closing this. :)
