### ISSUE TITLE
Certificate verification allows dangerous algorithms

### ISSUE THREAD

**Issue by emillon** [mirleft/ocaml-x509#123]
Hi,

Verification of a certificate chain does not check the signature algorithms themselves. At the moment, it should at least reject MD5 and SHA1 certificates. This is not a theoretical attack, there are SHA1 collisions, and it's possible to craft colliding MD5 certificates. As such, there's not much value in a valid signature based on these algorithms.

Browser vendors adopted [an interesting strategy to sunset SHA1](https://security.googleblog.com/2014/09/gradually-sunsetting-sha-1.html) (trusting them depending on when the certificate was issued), but that was several years ago - that is not necessary in 2019.

Thanks!

**Comment by hannesm** [comment]
> As such, there's not much value in a valid signature based on these algorithms.

I haven't seen an attack where someone presents a valid md5/sha1 certificate signed with my private key. (well, or taking an existing md5/sha1 cert produce a different (valid, elevating privileges) certificate and reuse the signature). do you have any pointer of such a published attack?

apart from that, I'll work on a patch which basically allows you to pass in a list of acceptable hash algorithms to `X509.Authenticator.chain_of_trust` (and likely intermediate functions in Validation), which then can be used by e.g. tls to whitelist algorithms.

**Comment by emillon** [comment]
The MD5 certificate collision is described in https://www.win.tue.nl/hashclash/rogue-ca/.

**Comment by psafont** [comment]
Is there a reason to not expose the Algorithm module at all? I have some requirements when certificates are checked, one of which is the type of algorithm used.

**Comment by hannesm** [comment]
@emillon thanks for your references

@psafont purely historical reasons, the API developed mainly out of demands for our OCaml-TLS stack.

It would be reasonable to provide a `X509.Certificate.signature_algorithm : X509.Certificate.t -> X509.Algorithm.t` (next to the whitelist of hash algorithms passed to the authenticators). I hope to get both done and released later this month.

**Comment by hannesm** [comment]
@psafont
> type of algorithm (hash) used

could you be more specific -- is it really only the hash algorithm, or as well the asymmetric algorithm (DSA/ECDSA/RSA) and/or padding strategy (PKCS1.2/PSS) used? And if it is a requirement, wouldn't a whitelist to the verification step be more suitable than a post-authentication retrieval of the algorithms used to sign the chain?

**Comment by psafont** [comment]
I'm not sure what you mean by "whitelist to the verification step".

The use-case is to verify server certificates generated and uploaded by users before using them. I'm aware it's not ideal at all and would rather use CSR to avoid doing the checks after the fact.

Currently the requirements specify only the hash, but for the API it would make sense to also expose the asymmetric algorithm as well, not sure about the padding strategy.

Adding this function to `lib/certificate.ml` does the trick for me:
```
let signature_algorithm { asn = cert ; _ } = Algorithm.to_signature_algorithm cert.signature_algo
```

I don't know how well it fits with the API design or the general case usage.

**Comment by hannesm** [comment]
> I'm not sure what you mean by "whitelist to the verification step".

see the comments above, extending the validation functions with an optional list of hash algorithms to be used during validation.

**Comment by psafont** [comment]
Unfortunately the trust anchor is not available so I cannot use verify_chain :(
