### ISSUE TITLE
RSA keys don't roundtrip?

### ISSUE THREAD

**Issue by anmonteiro** [mirleft/ocaml-x509#171]
forgive me if this is a dumb mistake on my part, but take this example:

```
# generate RSA priv key
$ openssl genpkey -algorithm RSA -out privatekey.pem -pkeyopt rsa_keygen_bits:2048

# extract the public key
$ openssl pkey -in privatekey.pem -pubout -out publickey.pem
```

and in a toplevel (e.g. utop):

```ocaml
#require "digestif.c";;
#require "x509";;

let x_pub = In_channel.input_all (In_channel.open_bin "./publickey.pem");;

let re_encoded =X509.Public_key.decode_pem x_pub |> Result.get_ok |> X509.Public_key.encode_pem;;

x_pub = re_encoded (* false *)

```

I'd expect these to roundtrip. In the previous version of X509 (before the Cstruct -> string migration), they did roundtrip:

```ocaml
let re_encoded = X509.Public_key.decode_pem (Cstruct.of_string x_pub) |> Result.get_ok |> X509.Public_key.encode_pem |> Cstruct.to_string;;

x = x_pub;;
- : bool = true
```

**Comment by hannesm** [comment]
Thanks for your report, I opened #172 with a regression test and a fix. If you could verify that this fixes your issue, that would be great.

I'll wait for CI, then merge and release.

**Comment by anmonteiro** [comment]
Thanks, that fixed RSA, but I think I might be seeing the same for P521?

**Comment by hannesm** [comment]
@anmonteiro would you mind to open a PR with a regression test? thanks a lot.
