### ISSUE TITLE
path building as in 4158

### ISSUE THREAD

**Issue by hannesm** [mirleft/ocaml-x509#53]
this is what we should implement... http://www.rfc-editor.org/rfc/rfc4158.txt all the strategies, making it configurable by a user (with a sensible default) -- related to #51

**Comment by briansmith** [comment]
It may be helpful to look at [libwebpki(https://github.com/briansmith/webpki). It uses a very similar strategy to what is used in [mozilla::pkix](https://github.com/briansmith/mozillapkix), which is what is used in Firefox. I don't think anything more complicated is necessary.
