### ISSUE TITLE
`sexplib.syntax` in installed META

### ISSUE THREAD

**Issue by paurkedal** [mirleft/ocaml-x509#55]
The current opam version of x509 installs a META which requires `sexplib.syntax`, and I can see the current _oasis lists it in BuildDepends.  I don't think that was intentional, and it conflicts with `deriving.syntax` which is why I discovered it.

**Comment by hannesm** [comment]
we actually require sexplib.syntax for building X.509 at the moment, there is a [`with sexp`](https://github.com/mirleft/ocaml-x509/blob/master/lib/x509_certificate.ml#L324)...

**Comment by paurkedal** [comment]
Yes, but the problem is that it ends up in the installed META.  BuildDepends does sound like it's safe for all build-time dependencies, so this should maybe a considered an issue in OASIS.  The OASIS META-plugin should probably filter out syntax extensions.  Putting syntax extensions directly in `_tags` avoids the issue.

**Comment by paurkedal** [comment]
I created an OASIS issue: https://forge.ocamlcore.org/tracker/index.php?func=detail&aid=1472&group_id=54&atid=291.

I also noticed that the META-plugin defines a `Requires`-field.  This overrides `BuildDepends` for the generated META, if present, so that would be an alternative way to make sure the META only requires what it needs to require.

**Comment by smondet** [comment]
I had the same problem, while looking for the problem, I found that @avsm had fixed it in `tls`:
https://github.com/mirleft/ocaml-tls/commit/7029199af34a4754ef75440f00edaaff2551941e

The same thing should be done for every lib that uses a `.syntax` package with Oasis.

**Comment by hannesm** [comment]
I've added a XMETARequires in #72
