### ISSUE TITLE
Retrieving valid_from/valid_until from a certificate

### ISSUE THREAD

**Issue by Engil** [mirleft/ocaml-x509#85]
Hello,

I currently need to get the dates defining when the certificate is valid. (to bind the functions in libnqsb-tls related to informations retrieval about the current peer)

It seems that those informations aren't currently exposed by the library, I had a chat with @hannesm that told me to open an issue, so here it is. :)

**Comment by hannesm** [comment]
these are `Time.t` from [asn1-combinators](https://github.com/mirleft/ocaml-asn1-combinators/blob/36c221b753dedc9b1d7d235391f738326ba92a3d/src/asn_time.mli#L2-L6), but should be `Ptime.t` (needs adjustment in asn1-combinator @pqwy) in the future
