### ISSUE TITLE
Cannot install due to dependency problem

### ISSUE THREAD

**Issue by pvaibhav** [mirleft/ocaml-x509#98]
I am trying to install via opam the `tls` package which depends on this (`x509`) package. I'm on up-to-date macOS with Ocaml 4.06.0. Unfortunately the installation fails due to dependency on `asn1-combinators < 0.2.0`.

```
$ opam install x509
The following dependencies couldn't be met:
  - x509 -> asn1-combinators < 0.2.0
  - x509 -> nocrypto < 0.5.2 -> sexplib < 113.01.00
  - x509 -> nocrypto < 0.5.2 -> ctypes < 0.4.0
Your request can't be satisfied:
  - asn1-combinators<0.2.0 is not available because your system doesn't comply with ocaml-version >= "4.01.0" & ocaml-version < "4.06.0".
  - ctypes<0.4.0 is not available because your system doesn't comply with ocaml-version >= "4.00.0" & ocaml-version < "4.03.0".
  - sexplib<113.01.00 is not available because your system doesn't comply with ocaml-version >= "4.02.1" & ocaml-version < "4.03".

No solution found, exiting

```

Furthermore, the previous version of `asn1-combinators` 0.1.3 cannot be installed due to compilation error.

Link to bug report for `tls` package: https://github.com/mirleft/ocaml-tls/issues/370

**Comment by hannesm** [comment]
thanks for the report, I'm very aware of this, but had been 9 days away from my keyboard organising a retreat.  soon there'll be both a x509 and a tls release - in the meantime you can use a 4.05.0 compiler to get started.

**Comment by hannesm** [comment]
X.509 0.6.0 is now as a PR to opam-repository https://github.com/ocaml/opam-repository/pull/11022 . TLS with support for this new X.509 needs another day or so.
